import React from 'react';
import commonTranslate from '../../../../translation/common.json';
export function listTableColumns(handleTableInputOnChange, handleDisabledDeleteButton, handleShowErrorModal, handleChangeModal) {

  return [
    {
      title: 'Comp #',
      dataIndex: 'distributionCompany',
      type: "alphaNumericInput",
      columnSortable: false,
      refId: 'cId',
      onChange: handleTableInputOnChange,
      onChangeField:handleChangeModal,
      isCheckValidation: true,
      maxLength: 3,
    },
    {
      title: '%',
      dataIndex: 'distributionPercent',
      type: "numericInput",
      columnSortable: false,
      refId: 'cId',
      onChange: handleTableInputOnChange,
      onChangeField:handleChangeModal,
      isCheckValidation: true,
      maxLength: 7,
    },
    {
      title: 'Salary',
      dataIndex: 'salaryAccount',
      type: "coaTextInput",
      columnSortable: false,
      refId: 'cId',
      onChange: handleTableInputOnChange,
      onChangeField:handleChangeModal,
      isCheckValidation: true,
      maxLength: 10,
    },
    {
      title: 'Overtime',
      dataIndex: 'overtimeAccount',
      type: "coaTextInput",
      columnSortable: false,
      refId: 'cId',
      onChange: handleTableInputOnChange,
      onChangeField:handleChangeModal,
      isCheckValidation: true,
      maxLength: 10,
    },
    {
      title: 'Vacation',
      dataIndex: 'vacationAccount',
      type: "coaTextInput",
      columnSortable: false,
      refId: 'cId',
      onChange: handleTableInputOnChange,
      onChangeField:handleChangeModal,
      isCheckValidation: true,
      maxLength: 10,
    },
    {
      title: 'Holiday',
      dataIndex: 'holidayAccount',
      type: "coaTextInput",
      columnSortable: false,
      refId: 'cId',
      onChange: handleTableInputOnChange,
      onChangeField:handleChangeModal,
      isCheckValidation: true,
      maxLength: 10,
    },
    {
      title: 'PTO',
      dataIndex: 'ptoAccount',
      type: "coaTextInput",
      columnSortable: false,
      refId: 'cId',
      onChange: handleTableInputOnChange,
      onChangeField:handleChangeModal,
      isCheckValidation: true,
      maxLength: 10,
    },
    {
      title: 'Retirement',
      dataIndex: 'employerRetirementAccount',
      type: "coaTextInput",
      columnSortable: false,
      refId: 'cId',
      onChange: handleTableInputOnChange,
      onChangeField:handleChangeModal,
      isCheckValidation: true,
      maxLength: 10,
    },
    {
      title: 'FICA',
      dataIndex: 'ficaAccount',
      type: "coaTextInput",
      columnSortable: false,
      refId: 'cId',
      onChange: handleTableInputOnChange,
      onChangeField:handleChangeModal,
      isCheckValidation: true,
      maxLength: 10,
    },
    {
      title: 'Medicare',
      dataIndex: 'medicareAccount',
      type: "coaTextInput",
      columnSortable: false,
      refId: 'cId',
      onChange: handleTableInputOnChange,
      onChangeField:handleChangeModal,
      isCheckValidation: true,
      maxLength: 10,
    },
    {
      title: 'FUTA',
      dataIndex: 'futaAccount',
      type: "coaTextInput",
      columnSortable: false,
      refId: 'cId',
      onChange: handleTableInputOnChange,
      onChangeField:handleChangeModal,
      isCheckValidation: true,
      maxLength: 10,
    },
    {
      title: 'SUTA',
      dataIndex: 'sutaAccount',
      type: "coaTextInput",
      columnSortable: false,
      refId: 'cId',
      onChange: handleTableInputOnChange,
      onChangeField:handleChangeModal,
      isCheckValidation: true,
      maxLength: 10,
    },
    {
      title: 'Compensation',
      dataIndex: 'workersCompensationAccount',
      type: "coaTextInput",
      columnSortable: false,
      refId: 'cId',
      onChange: handleTableInputOnChange,
      onChangeField:handleChangeModal,
      isCheckValidation: true,
      maxLength: 10,
    },
    {
      title: 'SDI',
      dataIndex: 'sdiAccount',
      type: "coaTextInput",
      columnSortable: false,
      refId: 'cId',
      onChange: handleTableInputOnChange,
      onChangeField:handleChangeModal,
      isCheckValidation: true,
      maxLength: 10,
    },
    {
      title: 'Contribution',
      dataIndex: 'employerContributionsAccount',
      type: "coaTextInput",
      columnSortable: false,
      refId: 'cId',
      onChange: handleTableInputOnChange,
      onChangeField:handleChangeModal,
      isCheckValidation: true,
      maxLength: 10,
    },
    {
      title: 'Action',
      dataIndex: 'extraData',
      type: "actionButtons",
      columnSortable: false,
      refId: 'cId',
      onChange: handleTableInputOnChange,
      onChangeField:handleChangeModal,
      isCheckValidation: true,
      maxLength: 25,
      actionButtons: [
        // {
        //   htmlId: "editAccount",
        //   buttonStyle: "primary",
        //   className: "btn btn-primary",
        //   text: commonTranslate.edit,
        //   type: "button",
        //   // onClick:handleEdit
        // },
        {
          htmlId: "deleteButton",
          buttonStyle: "danger",
          className: "table-delete-button",
          text: commonTranslate.delete,
          isDisabled: handleDisabledDeleteButton,
          onClick: handleShowErrorModal,
          type: "button"
        }
      ]
    },
  ]
}
