version: 0.2

env:
  variables:
    PublishDir: "build"
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build:dev
      - npm run test:ci
      - ls ./$PublishDir
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
  base-directory: "$PublishDir"
