export const CONFIG_USER_LIST = 'CONFIG_USER_LIST';
export const USER_FETCH_DETAIL = 'USER_FETCH_DETAIL';

// Admin Users
export const ADMIN_USER_LIST = 'ADMIN_USER_LIST';
export const ADMIN_USER_FETCH = 'ADMIN_USER_FETCH';
export const ADMIN_USER_REMOVE = 'ADMIN_USER_REMOVE';

// Enterprises
export const ENTERPRISE_ADD = 'ENTERPRISE_ADD';
export const ENTERPRISE_UPDATE = 'ENTERPRISE_UPDATE';
export const ENTERPRISE_REMOVE = 'ENTERPRISE_REMOVE';
export const ENTERPRISE_LIST = 'ENTERPRISE_LIST';
export const ENTERPRISE_FETCH = 'ENTERPRISE_FETCH';

// Workbook
export const WORKBOOK_FETCH = 'WORKBOOK_FETCH';
export const WORKBOOK_LIST = 'WORKBOOK_LIST';
export const WORKBOOK_COMPLETE = 'WORKBOOK_COMPLETE';

export const ACCESS_TYPES_SELECT_LIST = 'ACCESS_TYPES_SELECT_LIST';
export const DTID_SELECT_LIST = 'DTID_SELECT_LIST';
export const ENTERPRISE_CODE_SELECT_LIST = 'ENTERPRISE_CODE_SELECT_LIST';
export const STORE_SELECT_LIST = 'STORE_SELECT_LIST';
export const USER_SELECT_LIST = 'USER_SELECT_LIST';
export const WORKBOOK_SELECT_LIST = 'WORKBOOK_SELECT_LIST';
export const WORKBOOK_ACCESS_SELECT_LIST = 'WORKBOOK_ACCESS_SELECT_LIST';
export const COMPANY_SELECT_LIST = 'COMPANY_SELECT_LIST';

// Workbook Section
export const WORKBOOK_SECTION_FETCH = 'WORKBOOK_SECTION_FETCH';
export const WORKBOOK_SECTION_ADD = 'WORKBOOK_SECTION_ADD';
export const WORKBOOK_SECTION_UPDATE = 'WORKBOOK_SECTION_UPDATE';

// Menus
export const MENU_LIST = 'MENU_LIST';
export const MENU_SECTION_LIST = 'MENU_SECTION_LIST';
export const USER_ACCESS_WORKBOOK_FETCH = 'USER_ACCESS_WORKBOOK_FETCH';

// Data Transaction
export const EXPORT_DATA_TRANSACTION = 'EXPORT_DATA_TRANSACTION';
export const IMPORT_DATA_TRANSACTION = 'IMPORT_DATA_TRANSACTION';
export const PROCESS_DATA_TRANSACTION = 'PROCESS_DATA_TRANSACTION';
export const PROCESS_COPY_DATA = 'PROCESS_COPY_DATA';
export const FETCH_DATA_TRANSACTION = 'FETCH_DATA_TRANSACTION';
export const SAVE_DATA_TRANSACTION = 'SAVE_DATA_TRANSACTION';
export const BATCH_UPDATE_BY_FIELD = 'BATCH_UPDATE_BY_FIELD';

// Chart of Accounts
export const REVIEW_ACCOUNTS_LIST = 'REVIEW_ACCOUNTS_LIST';
export const UPDATE_REVIEW_ACCOUNTS_LIST = 'UPDATE_REVIEW_ACCOUNTS_LIST';
export const UPDATE_REVIEW_ACCOUNTS = 'UPDATE_REVIEW_ACCOUNTS';
export const ADD_REVIEW_ACCOUNTS = 'ADD_REVIEW_ACCOUNTS';
export const SET_COA_PREFIX = 'SET_COA_PREFIX';

// Accounting
export const BANK_ACCOUNT_LIST = 'BANK_ACCOUNT_LIST';
export const ACCOUNTING_SECTION_LIST = 'ACCOUNTING_SECTION_LIST';
export const ACCOUNTING_SECTION_FETCH = 'ACCOUNTING_SECTION_FETCH';
export const ACCOUNTING_LIST_REMOVE = 'ACCOUNTING_LIST_REMOVE';

// Sales FI
export const SALES_FI_SECTION_FETCH = 'SALES_FI_SECTION_FETCH';
export const SALES_FI_LIST_REMOVE = 'SALES_FI_LIST_REMOVE';
export const SALES_FI_SECTION_LIST = 'SALES_FI_SECTION_LIST';

// Parts
export const PARTS_SECTION_FETCH = 'PARTS_SECTION_FETCH';
export const PARTS_LIST_REMOVE = 'PARTS_LIST_REMOVE';
export const PARTS_SECTION_LIST = 'PARTS_SECTION_LIST';

// Service
export const SERVICE_SECTION_FETCH = 'SERVICE_SECTION_FETCH';
export const SERVICE_LIST_REMOVE = 'SERVICE_LIST_REMOVE';
export const SERVICE_SECTION_LIST = 'SERVICE_SECTION_LIST';

// Payroll
export const PAYROLL_SECTION_FETCH = 'PAYROLL_SECTION_FETCH';
export const PAYROLL_LIST_REMOVE = 'PAYROLL_LIST_REMOVE';
export const PAYROLL_SECTION_LIST = 'PAYROLL_SECTION_LIST';

// Auth
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// User Store
export const USER_STORE_LIST = 'USER_STORE_LIST';

// Clear Data
export const CLEAR_DATA = 'CLEAR_DATA';
